name: run-unit-tests
run-name: ${{ github.actor }} triggered this run
on: [push]

env:
  KEY: ${{ secrets.KEY }}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install pipenv
        run: |
          python -m pip install --upgrade pipenv wheel
      - name: Install dependencies
        run: |
          cd metadata-clean-up
          pip install -r requirements.txt
      - name: Test with pytest
        run: |
          pytest